<a href="https://colab.research.google.com/github/jadhavritesh2202/diabetes-prediction-ml/blob/main/Diabetes_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Importing the Depedencies**

In [3]:
import numpy as np

**Logistic Regression**

In [27]:
class Logistic_Regression():

  #self-> is the reference instant(object)
  #while creating a object we will give value of learning rate nd number of iteration
  # declaring learning rate & number of iterations (hyperparameters)
  def __init__(self, learning_rate, no_of_iterations):

    self.learning_rate = learning_rate
    self.no_of_iterations = no_of_iterations

  def fit(self, X, Y):#X=no.of features Y=training
  # number of data points & number of features
  # m-> no.of rows and n-> no.of cols

    self.m, self.n = X.shape #(769,8)
     # initiating the weights & bias
    self.w = np.zeros(self.n) # 8 cols
    self.b = 0
    self.X = X
    self.Y = Y

     #loop till no of iteration and change weight & bias value
     #gradient descent
    for i in range(self.no_of_iterations):
      self.update_weights(X,Y)
      #function to update weights & bias value
  def update_weights(self, X, Y):
       #y_hat formula(sigmoid fun)  Z = wX + b
       Y_hat = 1 / (1 + np.exp(-(self.X.dot(self.w) + self.b)))

        # derivatives    X=[769,8] Y=[769,1] (take transpose of X) then multiply(.)
       dw=(1/self.m)*np.dot(self.X.T , (Y_hat - self.Y))
       db=(1/self.m)*np.sum(Y_hat - self.Y)
       # updating the weights & bias using gradient descent
       self.w = self.w - self.learning_rate * dw
       self.b = self.b - self.learning_rate * db






  def predict(self, X):

    Y_pred = 1 / (1 + np.exp( - (X.dot(self.w) + self.b ) ))
    Y_pred = np.where( Y_pred > 0.5, 1, 0)
    return Y_pred

**Train Model**

In [5]:
#import libraries
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
# import Logistic_Regression_Model as lr

**Data Collections and Analysis**

In [7]:
#loading the dataset
diabetes_dataset=pd.read_csv("/content/diabetes.csv")

In [5]:
#print first 5
diabetes_dataset.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [8]:
#no of rows and cols
diabetes_dataset.shape

(768, 9)

In [9]:
#getting statistical measures of the data
diabetes_dataset.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [10]:
diabetes_dataset['Outcome'].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

0-> Non-Diabetic
1-> Diabetic

In [11]:
diabetes_dataset.groupby('Outcome').mean()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
Outcome,,,,,,,,
0,3.298000,109.980000,68.184000,19.664000,68.792000,30.304200,0.429734,31.190000
1,4.865672,141.257463,70.824627,22.164179,100.335821,35.142537,0.550500,37.067164

In [12]:
#separate features and label
features=diabetes_dataset.drop(columns='Outcome',axis=1)
target=diabetes_dataset['Outcome']

In [13]:
print(features)

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6
1              1       85             66             29        0  26.6
2              8      183             64              0        0  23.3
3              1       89             66             23       94  28.1
4              0      137             40             35      168  43.1
..           ...      ...            ...            ...      ...   ...
763           10      101             76             48      180  32.9
764            2      122             70             27        0  36.8
765            5      121             72             23      112  26.2
766            1      126             60              0        0  30.1
767            1       93             70             31        0  30.4

     DiabetesPedigreeFunction  Age
0                       0.627   50
1                       0.351   31
2                       0.672   32
3                       0.167   21
4                       2.288   33
..                        ...  ...
763                     0.171   63
764                     0.340   27
765                     0.245   30
766                     0.349   47
767                     0.315   23

[768 rows x 8 columns]

In [13]:
print(target)

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

**Data Standardization** (it becomes valid range)

In [14]:
scalar=StandardScaler()

In [17]:
# fit() → learns mean and std
# transform() → applies formula
# fit_transform() → both together
standardized_data=scalar.fit_transform(features)

In [18]:
print(standardized_data)

[[ 0.63994726  0.84832379  0.14964075 ...  0.20401277  0.46849198
   1.4259954 ]
 [-0.84488505 -1.12339636 -0.16054575 ... -0.68442195 -0.36506078
  -0.19067191]
 [ 1.23388019  1.94372388 -0.26394125 ... -1.10325546  0.60439732
  -0.10558415]
 ...
 [ 0.3429808   0.00330087  0.14964075 ... -0.73518964 -0.68519336
  -0.27575966]
 [-0.84488505  0.1597866  -0.47073225 ... -0.24020459 -0.37110101
   1.17073215]
 [-0.84488505 -0.8730192   0.04624525 ... -0.20212881 -0.47378505
  -0.87137393]]

In [19]:
#saving standardize data into features
features=standardized_data
target=diabetes_dataset['Outcome']

In [20]:
print(features)

[[ 0.63994726  0.84832379  0.14964075 ...  0.20401277  0.46849198
   1.4259954 ]
 [-0.84488505 -1.12339636 -0.16054575 ... -0.68442195 -0.36506078
  -0.19067191]
 [ 1.23388019  1.94372388 -0.26394125 ... -1.10325546  0.60439732
  -0.10558415]
 ...
 [ 0.3429808   0.00330087  0.14964075 ... -0.73518964 -0.68519336
  -0.27575966]
 [-0.84488505  0.1597866  -0.47073225 ... -0.24020459 -0.37110101
   1.17073215]
 [-0.84488505 -0.8730192   0.04624525 ... -0.20212881 -0.47378505
  -0.87137393]]

In [21]:
print(target)

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

**Train Test Split**

In [22]:
X_train,X_test,Y_train,Y_test=train_test_split(features,target,test_size=0.2,random_state=2)

In [23]:
print(features.shape,X_train.shape,X_test.shape)

(768, 8) (614, 8) (154, 8)

**Now Training The Model**

In [28]:
#call the Logistic model with input value
classifier=Logistic_Regression(learning_rate=0.01,no_of_iterations=1000)
# classifier=lr.Logistic_Regression(learning_rate=0.01,no_of_iterations=1000)

In [29]:
#now fit the data
classifier.fit(X_train, Y_train)

**Model Evaluation**

**Accuracy Score**

In [30]:
#accuracy score on training data
X_train_prediction=classifier.predict(X_train) #predicted by model
training_data_accuracy=accuracy_score(Y_train,X_train_prediction) #compare with test(Y_Train)

In [32]:
print("Accuracy score of the train data:" ,training_data_accuracy)

Accuracy score of the test data: 0.7768729641693811

In [33]:
#accuracy score on test data
X_test_prediction=classifier.predict(X_test) #predicted by model
test_data_accuracy=accuracy_score(Y_test,X_test_prediction) #compare with test(Y_Train)

In [34]:
print("Accuracy score of the test data:" ,test_data_accuracy)

Accuracy score of the test data: 0.7662337662337663

**Making Predictive System**

*After training, we want to test a NEW patient.*

In [35]:
#changing input data to numpy array
input_data=np.asarray([5,166,72,19,175,25.8,0.587,51])
#reshape the array as we are predicting for one instance
input_data_reshaped=input_data.reshape(1,-1)

In [36]:
#standardize input data
std_data=scalar.transform(input_data_reshaped)
print(std_data)

[[ 0.3429808   1.41167241  0.14964075 -0.09637905  0.82661621 -0.78595734
   0.34768723  1.51108316]]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [37]:
prediction=classifier.predict(std_data)
print(prediction)

[1]

In [38]:
if(prediction[0]==0):
  print("The person is not diabetic")
else:
  print("The person is diabetic")

The person is diabetic